### ISSUE TITLE
Problem in Solving

### ISSUE THREAD

**Issue by mohsenboojari** [petebachant/NTNU-HAWT-turbinesFoam#13]
I tried to run the case but I got this Error in pimpleFoam log file. what could be the reason?

((` Creating finite volume options from "system/fvOptions"

Selecting finite volume options model type axialFlowTurbineALSource
    Source: turbine1
    - selecting cells using cellSet turbine1

--> FOAM FATAL ERROR: 
Cannot find directory "polyMesh/sets" in times 0 down to constant

```
From function Time::findInstance(const fileName&, const word&, const IOobject::readOption, const word&)
in file db/Time/findInstance.C at line 142.
```

FOAM exiting `))
I have changed the Debug switches in controlDict . does it have any effects on this issu?

**Comment by petebachant** [comment]
Did you run the case with `./Allrun`? It sounds like `topoSet` was either not called or did not execute properly.

**Comment by mohsenboojari** [comment]
I also faced with a problem when tried to run sample !
this is the Error : 
`Time = 0
--> FOAM Warning : 
    From function sampledSets::classifyFields()
    in file sampledSet/sampledSets/sampledSetsGrouping.C at line 109
    Cannot find field file matching UMean
--> FOAM Warning : 
    From function sampledSets::classifyFields()
    in file sampledSet/sampledSets/sampledSetsGrouping.C at line 109
    Cannot find field file matching UPrime2Mean
--> FOAM Warning : 
    From function sampledSets::classifyFields()
    in file sampledSet/sampledSets/sampledSetsGrouping.C at line 109
    Cannot find field file matching kMean
--> FOAM Warning : 
    From function sampledSets::classifyFields()
    in file sampledSet/sampledSets/sampledSetsGrouping.C at line 109
    Cannot find field file matching RMeanXX` 

whats wrong with this?

**Comment by petebachant** [comment]
If you read the error message, `sample` is telling you those fields don't exist to be sampled. If you look in `scripts/Allrun.post`, the sampling is meant to be done at the end of the simulation with `sample -latestTime`, since that is the only time those fields are written.
