### ISSUE TITLE
Blade data for the turbine

### ISSUE THREAD

**Issue by hcOnel** [petebachant/NTNU-HAWT-turbinesFoam#16]
I've searched but could not find the blade geometry and pitching vs free stream velocity data for the NTNU turbine. Can you please share the source, if possible?

**Comment by petebachant** [comment]
Sorry I missed this. The turbine parameters can be seen here: https://drive.google.com/file/d/0BwMVIAlxIxfZMlhXWEhWR0JhVHM/view?usp=sharing

I'm pretty sure the rotors are fixed pitch.
